<?xml version="1.0" encoding="utf-8"?><Database Name="QLVEMB" Class="VemayBayDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-CU2DB44\SQLEXPRESS;Initial Catalog=QLVEMB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLVEMBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUYENBAY" Member="CHUYENBAYs">
    <Type Name="CHUYENBAY">
      <Column Name="MaChuyenBay" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMayBay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaDau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaCuoi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioBay" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioDen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHUYENBAY_VEBAN" Member="VEBANs" ThisKey="MaChuyenBay" OtherKey="MaChuyenBay" Type="VEBAN" />
      <Association Name="DIEMCUOI_CHUYENBAY" Member="DIEMCUOI" ThisKey="MaCuoi" OtherKey="MaCuoi" Type="DIEMCUOI" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="DIEMDAU_CHUYENBAY" Member="DIEMDAU" ThisKey="MaDau" OtherKey="MaDau" Type="DIEMDAU" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="MAYBAY_CHUYENBAY" Member="MAYBAY" ThisKey="MaMayBay" OtherKey="MaMayBay" Type="MAYBAY" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VEBAN" Member="VEBANs">
    <Type Name="VEBAN">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SLVeBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaChuyenBay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TongGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CHUYENBAY_VEBAN" Member="CHUYENBAY" ThisKey="MaChuyenBay" OtherKey="MaChuyenBay" Type="CHUYENBAY" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="KHACHHANG_VEBAN" Member="KHACHHANG" ThisKey="CMND" OtherKey="CMND" Type="KHACHHANG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="LOAIVE_VEBAN" Member="LOAIVE" ThisKey="MaLoai" OtherKey="MaLoai" Type="LOAIVE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NHANVIEN_VEBAN" Member="NHANVIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIEMCUOI" Member="DIEMCUOIs">
    <Type Name="DIEMCUOI">
      <Column Name="MaCuoi" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DIEMCUOI_CHUYENBAY" Member="CHUYENBAYs" ThisKey="MaCuoi" OtherKey="MaCuoi" Type="CHUYENBAY" />
    </Type>
  </Table>
  <Table Name="dbo.DIEMDAU" Member="DIEMDAUs">
    <Type Name="DIEMDAU">
      <Column Name="MaDau" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenD" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DIEMDAU_CHUYENBAY" Member="CHUYENBAYs" ThisKey="MaDau" OtherKey="MaDau" Type="CHUYENBAY" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="CMND" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ngaysinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_VEBAN" Member="VEBANs" ThisKey="CMND" OtherKey="CMND" Type="VEBAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIVE" Member="LOAIVEs">
    <Type Name="LOAIVE">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAIVE_VEBAN" Member="VEBANs" ThisKey="MaLoai" OtherKey="MaLoai" Type="VEBAN" />
    </Type>
  </Table>
  <Table Name="dbo.MAYBAY" Member="MAYBAYs">
    <Type Name="MAYBAY">
      <Column Name="MaMayBay" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMayBay" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoGheLTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoGheLT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MAYBAY_CHUYENBAY" Member="CHUYENBAYs" ThisKey="MaMayBay" OtherKey="MaMayBay" Type="CHUYENBAY" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AnhNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHANVIEN_VEBAN" Member="VEBANs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="VEBAN" />
    </Type>
  </Table>
  <Table Name="dbo.THONGBAO" Member="THONGBAOs">
    <Type Name="THONGBAO">
      <Column Name="MaThongBao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>