#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuoiKy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVEMB")]
	public partial class VemayBayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUYENBAY(CHUYENBAY instance);
    partial void UpdateCHUYENBAY(CHUYENBAY instance);
    partial void DeleteCHUYENBAY(CHUYENBAY instance);
    partial void InsertVEBAN(VEBAN instance);
    partial void UpdateVEBAN(VEBAN instance);
    partial void DeleteVEBAN(VEBAN instance);
    partial void InsertDIEMCUOI(DIEMCUOI instance);
    partial void UpdateDIEMCUOI(DIEMCUOI instance);
    partial void DeleteDIEMCUOI(DIEMCUOI instance);
    partial void InsertDIEMDAU(DIEMDAU instance);
    partial void UpdateDIEMDAU(DIEMDAU instance);
    partial void DeleteDIEMDAU(DIEMDAU instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIVE(LOAIVE instance);
    partial void UpdateLOAIVE(LOAIVE instance);
    partial void DeleteLOAIVE(LOAIVE instance);
    partial void InsertMAYBAY(MAYBAY instance);
    partial void UpdateMAYBAY(MAYBAY instance);
    partial void DeleteMAYBAY(MAYBAY instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertTHONGBAO(THONGBAO instance);
    partial void UpdateTHONGBAO(THONGBAO instance);
    partial void DeleteTHONGBAO(THONGBAO instance);
    #endregion
		
		public VemayBayDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLVEMBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VemayBayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VemayBayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VemayBayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VemayBayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUYENBAY> CHUYENBAYs
		{
			get
			{
				return this.GetTable<CHUYENBAY>();
			}
		}
		
		public System.Data.Linq.Table<VEBAN> VEBANs
		{
			get
			{
				return this.GetTable<VEBAN>();
			}
		}
		
		public System.Data.Linq.Table<DIEMCUOI> DIEMCUOIs
		{
			get
			{
				return this.GetTable<DIEMCUOI>();
			}
		}
		
		public System.Data.Linq.Table<DIEMDAU> DIEMDAUs
		{
			get
			{
				return this.GetTable<DIEMDAU>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIVE> LOAIVEs
		{
			get
			{
				return this.GetTable<LOAIVE>();
			}
		}
		
		public System.Data.Linq.Table<MAYBAY> MAYBAYs
		{
			get
			{
				return this.GetTable<MAYBAY>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<THONGBAO> THONGBAOs
		{
			get
			{
				return this.GetTable<THONGBAO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYENBAY")]
	public partial class CHUYENBAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuyenBay;
		
		private int _MaMayBay;
		
		private string _MaDau;
		
		private string _MaCuoi;
		
		private string _NgayDi;
		
		private string _NgayDen;
		
		private string _GioBay;
		
		private string _GioDen;
		
		private string _GhiChu;
		
		private EntitySet<VEBAN> _VEBANs;
		
		private EntityRef<DIEMCUOI> _DIEMCUOI;
		
		private EntityRef<DIEMDAU> _DIEMDAU;
		
		private EntityRef<MAYBAY> _MAYBAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuyenBayChanging(int value);
    partial void OnMaChuyenBayChanged();
    partial void OnMaMayBayChanging(int value);
    partial void OnMaMayBayChanged();
    partial void OnMaDauChanging(string value);
    partial void OnMaDauChanged();
    partial void OnMaCuoiChanging(string value);
    partial void OnMaCuoiChanged();
    partial void OnNgayDiChanging(string value);
    partial void OnNgayDiChanged();
    partial void OnNgayDenChanging(string value);
    partial void OnNgayDenChanged();
    partial void OnGioBayChanging(string value);
    partial void OnGioBayChanged();
    partial void OnGioDenChanging(string value);
    partial void OnGioDenChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CHUYENBAY()
		{
			this._VEBANs = new EntitySet<VEBAN>(new Action<VEBAN>(this.attach_VEBANs), new Action<VEBAN>(this.detach_VEBANs));
			this._DIEMCUOI = default(EntityRef<DIEMCUOI>);
			this._DIEMDAU = default(EntityRef<DIEMDAU>);
			this._MAYBAY = default(EntityRef<MAYBAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenBay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChuyenBay
		{
			get
			{
				return this._MaChuyenBay;
			}
			set
			{
				if ((this._MaChuyenBay != value))
				{
					this.OnMaChuyenBayChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenBay = value;
					this.SendPropertyChanged("MaChuyenBay");
					this.OnMaChuyenBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMayBay", DbType="Int NOT NULL")]
		public int MaMayBay
		{
			get
			{
				return this._MaMayBay;
			}
			set
			{
				if ((this._MaMayBay != value))
				{
					if (this._MAYBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMayBayChanging(value);
					this.SendPropertyChanging();
					this._MaMayBay = value;
					this.SendPropertyChanged("MaMayBay");
					this.OnMaMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaDau
		{
			get
			{
				return this._MaDau;
			}
			set
			{
				if ((this._MaDau != value))
				{
					if (this._DIEMDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDauChanging(value);
					this.SendPropertyChanging();
					this._MaDau = value;
					this.SendPropertyChanged("MaDau");
					this.OnMaDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCuoi
		{
			get
			{
				return this._MaCuoi;
			}
			set
			{
				if ((this._MaCuoi != value))
				{
					if (this._DIEMCUOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCuoiChanging(value);
					this.SendPropertyChanging();
					this._MaCuoi = value;
					this.SendPropertyChanged("MaCuoi");
					this.OnMaCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this.OnNgayDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDi = value;
					this.SendPropertyChanged("NgayDi");
					this.OnNgayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NgayDen
		{
			get
			{
				return this._NgayDen;
			}
			set
			{
				if ((this._NgayDen != value))
				{
					this.OnNgayDenChanging(value);
					this.SendPropertyChanging();
					this._NgayDen = value;
					this.SendPropertyChanged("NgayDen");
					this.OnNgayDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioBay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GioBay
		{
			get
			{
				return this._GioBay;
			}
			set
			{
				if ((this._GioBay != value))
				{
					this.OnGioBayChanging(value);
					this.SendPropertyChanging();
					this._GioBay = value;
					this.SendPropertyChanged("GioBay");
					this.OnGioBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioDen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GioDen
		{
			get
			{
				return this._GioDen;
			}
			set
			{
				if ((this._GioDen != value))
				{
					this.OnGioDenChanging(value);
					this.SendPropertyChanging();
					this._GioDen = value;
					this.SendPropertyChanged("GioDen");
					this.OnGioDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENBAY_VEBAN", Storage="_VEBANs", ThisKey="MaChuyenBay", OtherKey="MaChuyenBay")]
		public EntitySet<VEBAN> VEBANs
		{
			get
			{
				return this._VEBANs;
			}
			set
			{
				this._VEBANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMCUOI_CHUYENBAY", Storage="_DIEMCUOI", ThisKey="MaCuoi", OtherKey="MaCuoi", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DIEMCUOI DIEMCUOI
		{
			get
			{
				return this._DIEMCUOI.Entity;
			}
			set
			{
				DIEMCUOI previousValue = this._DIEMCUOI.Entity;
				if (((previousValue != value) 
							|| (this._DIEMCUOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEMCUOI.Entity = null;
						previousValue.CHUYENBAYs.Remove(this);
					}
					this._DIEMCUOI.Entity = value;
					if ((value != null))
					{
						value.CHUYENBAYs.Add(this);
						this._MaCuoi = value.MaCuoi;
					}
					else
					{
						this._MaCuoi = default(string);
					}
					this.SendPropertyChanged("DIEMCUOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDAU_CHUYENBAY", Storage="_DIEMDAU", ThisKey="MaDau", OtherKey="MaDau", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DIEMDAU DIEMDAU
		{
			get
			{
				return this._DIEMDAU.Entity;
			}
			set
			{
				DIEMDAU previousValue = this._DIEMDAU.Entity;
				if (((previousValue != value) 
							|| (this._DIEMDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEMDAU.Entity = null;
						previousValue.CHUYENBAYs.Remove(this);
					}
					this._DIEMDAU.Entity = value;
					if ((value != null))
					{
						value.CHUYENBAYs.Add(this);
						this._MaDau = value.MaDau;
					}
					else
					{
						this._MaDau = default(string);
					}
					this.SendPropertyChanged("DIEMDAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAYBAY_CHUYENBAY", Storage="_MAYBAY", ThisKey="MaMayBay", OtherKey="MaMayBay", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public MAYBAY MAYBAY
		{
			get
			{
				return this._MAYBAY.Entity;
			}
			set
			{
				MAYBAY previousValue = this._MAYBAY.Entity;
				if (((previousValue != value) 
							|| (this._MAYBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAYBAY.Entity = null;
						previousValue.CHUYENBAYs.Remove(this);
					}
					this._MAYBAY.Entity = value;
					if ((value != null))
					{
						value.CHUYENBAYs.Add(this);
						this._MaMayBay = value.MaMayBay;
					}
					else
					{
						this._MaMayBay = default(int);
					}
					this.SendPropertyChanged("MAYBAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENBAY = this;
		}
		
		private void detach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENBAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VEBAN")]
	public partial class VEBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MaLoai;
		
		private int _SLVeBan;
		
		private int _MaNhanVien;
		
		private string _CMND;
		
		private int _MaChuyenBay;
		
		private int _TongGia;
		
		private EntityRef<CHUYENBAY> _CHUYENBAY;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAIVE> _LOAIVE;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnSLVeBanChanging(int value);
    partial void OnSLVeBanChanged();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnMaChuyenBayChanging(int value);
    partial void OnMaChuyenBayChanged();
    partial void OnTongGiaChanging(int value);
    partial void OnTongGiaChanged();
    #endregion
		
		public VEBAN()
		{
			this._CHUYENBAY = default(EntityRef<CHUYENBAY>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAIVE = default(EntityRef<LOAIVE>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LOAIVE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLVeBan", DbType="Int NOT NULL")]
		public int SLVeBan
		{
			get
			{
				return this._SLVeBan;
			}
			set
			{
				if ((this._SLVeBan != value))
				{
					this.OnSLVeBanChanging(value);
					this.SendPropertyChanging();
					this._SLVeBan = value;
					this.SendPropertyChanged("SLVeBan");
					this.OnSLVeBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL")]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenBay", DbType="Int NOT NULL")]
		public int MaChuyenBay
		{
			get
			{
				return this._MaChuyenBay;
			}
			set
			{
				if ((this._MaChuyenBay != value))
				{
					if (this._CHUYENBAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenBayChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenBay = value;
					this.SendPropertyChanged("MaChuyenBay");
					this.OnMaChuyenBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGia", DbType="Int NOT NULL")]
		public int TongGia
		{
			get
			{
				return this._TongGia;
			}
			set
			{
				if ((this._TongGia != value))
				{
					this.OnTongGiaChanging(value);
					this.SendPropertyChanging();
					this._TongGia = value;
					this.SendPropertyChanged("TongGia");
					this.OnTongGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENBAY_VEBAN", Storage="_CHUYENBAY", ThisKey="MaChuyenBay", OtherKey="MaChuyenBay", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CHUYENBAY CHUYENBAY
		{
			get
			{
				return this._CHUYENBAY.Entity;
			}
			set
			{
				CHUYENBAY previousValue = this._CHUYENBAY.Entity;
				if (((previousValue != value) 
							|| (this._CHUYENBAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUYENBAY.Entity = null;
						previousValue.VEBANs.Remove(this);
					}
					this._CHUYENBAY.Entity = value;
					if ((value != null))
					{
						value.VEBANs.Add(this);
						this._MaChuyenBay = value.MaChuyenBay;
					}
					else
					{
						this._MaChuyenBay = default(int);
					}
					this.SendPropertyChanged("CHUYENBAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_VEBAN", Storage="_KHACHHANG", ThisKey="CMND", OtherKey="CMND", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.VEBANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.VEBANs.Add(this);
						this._CMND = value.CMND;
					}
					else
					{
						this._CMND = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIVE_VEBAN", Storage="_LOAIVE", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LOAIVE LOAIVE
		{
			get
			{
				return this._LOAIVE.Entity;
			}
			set
			{
				LOAIVE previousValue = this._LOAIVE.Entity;
				if (((previousValue != value) 
							|| (this._LOAIVE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIVE.Entity = null;
						previousValue.VEBANs.Remove(this);
					}
					this._LOAIVE.Entity = value;
					if ((value != null))
					{
						value.VEBANs.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("LOAIVE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VEBAN", Storage="_NHANVIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.VEBANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.VEBANs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEMCUOI")]
	public partial class DIEMCUOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCuoi;
		
		private string _TenC;
		
		private EntitySet<CHUYENBAY> _CHUYENBAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCuoiChanging(string value);
    partial void OnMaCuoiChanged();
    partial void OnTenCChanging(string value);
    partial void OnTenCChanged();
    #endregion
		
		public DIEMCUOI()
		{
			this._CHUYENBAYs = new EntitySet<CHUYENBAY>(new Action<CHUYENBAY>(this.attach_CHUYENBAYs), new Action<CHUYENBAY>(this.detach_CHUYENBAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCuoi
		{
			get
			{
				return this._MaCuoi;
			}
			set
			{
				if ((this._MaCuoi != value))
				{
					this.OnMaCuoiChanging(value);
					this.SendPropertyChanging();
					this._MaCuoi = value;
					this.SendPropertyChanged("MaCuoi");
					this.OnMaCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenC
		{
			get
			{
				return this._TenC;
			}
			set
			{
				if ((this._TenC != value))
				{
					this.OnTenCChanging(value);
					this.SendPropertyChanging();
					this._TenC = value;
					this.SendPropertyChanged("TenC");
					this.OnTenCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMCUOI_CHUYENBAY", Storage="_CHUYENBAYs", ThisKey="MaCuoi", OtherKey="MaCuoi")]
		public EntitySet<CHUYENBAY> CHUYENBAYs
		{
			get
			{
				return this._CHUYENBAYs;
			}
			set
			{
				this._CHUYENBAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.DIEMCUOI = this;
		}
		
		private void detach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.DIEMCUOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEMDAU")]
	public partial class DIEMDAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDau;
		
		private string _TenD;
		
		private EntitySet<CHUYENBAY> _CHUYENBAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDauChanging(string value);
    partial void OnMaDauChanged();
    partial void OnTenDChanging(string value);
    partial void OnTenDChanged();
    #endregion
		
		public DIEMDAU()
		{
			this._CHUYENBAYs = new EntitySet<CHUYENBAY>(new Action<CHUYENBAY>(this.attach_CHUYENBAYs), new Action<CHUYENBAY>(this.detach_CHUYENBAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDau", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDau
		{
			get
			{
				return this._MaDau;
			}
			set
			{
				if ((this._MaDau != value))
				{
					this.OnMaDauChanging(value);
					this.SendPropertyChanging();
					this._MaDau = value;
					this.SendPropertyChanged("MaDau");
					this.OnMaDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenD
		{
			get
			{
				return this._TenD;
			}
			set
			{
				if ((this._TenD != value))
				{
					this.OnTenDChanging(value);
					this.SendPropertyChanging();
					this._TenD = value;
					this.SendPropertyChanged("TenD");
					this.OnTenDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDAU_CHUYENBAY", Storage="_CHUYENBAYs", ThisKey="MaDau", OtherKey="MaDau")]
		public EntitySet<CHUYENBAY> CHUYENBAYs
		{
			get
			{
				return this._CHUYENBAYs;
			}
			set
			{
				this._CHUYENBAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDAU = this;
		}
		
		private void detach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CMND;
		
		private string _TenKhachHang;
		
		private bool _GioiTinh;
		
		private string _Ngaysinh;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private EntitySet<VEBAN> _VEBANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnNgaysinhChanging(string value);
    partial void OnNgaysinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._VEBANs = new EntitySet<VEBAN>(new Action<VEBAN>(this.attach_VEBANs), new Action<VEBAN>(this.detach_VEBANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_VEBAN", Storage="_VEBANs", ThisKey="CMND", OtherKey="CMND")]
		public EntitySet<VEBAN> VEBANs
		{
			get
			{
				return this._VEBANs;
			}
			set
			{
				this._VEBANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIVE")]
	public partial class LOAIVE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private string _Gia;
		
		private EntitySet<VEBAN> _VEBANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    #endregion
		
		public LOAIVE()
		{
			this._VEBANs = new EntitySet<VEBAN>(new Action<VEBAN>(this.attach_VEBANs), new Action<VEBAN>(this.detach_VEBANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIVE_VEBAN", Storage="_VEBANs", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<VEBAN> VEBANs
		{
			get
			{
				return this._VEBANs;
			}
			set
			{
				this._VEBANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIVE = this;
		}
		
		private void detach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIVE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAYBAY")]
	public partial class MAYBAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMayBay;
		
		private string _TenMayBay;
		
		private string _HangSanXuat;
		
		private int _SoGheLTG;
		
		private int _SoGheLT;
		
		private EntitySet<CHUYENBAY> _CHUYENBAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMayBayChanging(int value);
    partial void OnMaMayBayChanged();
    partial void OnTenMayBayChanging(string value);
    partial void OnTenMayBayChanged();
    partial void OnHangSanXuatChanging(string value);
    partial void OnHangSanXuatChanged();
    partial void OnSoGheLTGChanging(int value);
    partial void OnSoGheLTGChanged();
    partial void OnSoGheLTChanging(int value);
    partial void OnSoGheLTChanged();
    #endregion
		
		public MAYBAY()
		{
			this._CHUYENBAYs = new EntitySet<CHUYENBAY>(new Action<CHUYENBAY>(this.attach_CHUYENBAYs), new Action<CHUYENBAY>(this.detach_CHUYENBAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMayBay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMayBay
		{
			get
			{
				return this._MaMayBay;
			}
			set
			{
				if ((this._MaMayBay != value))
				{
					this.OnMaMayBayChanging(value);
					this.SendPropertyChanging();
					this._MaMayBay = value;
					this.SendPropertyChanged("MaMayBay");
					this.OnMaMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMayBay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMayBay
		{
			get
			{
				return this._TenMayBay;
			}
			set
			{
				if ((this._TenMayBay != value))
				{
					this.OnTenMayBayChanging(value);
					this.SendPropertyChanging();
					this._TenMayBay = value;
					this.SendPropertyChanged("TenMayBay");
					this.OnTenMayBayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSanXuat", DbType="NVarChar(50)")]
		public string HangSanXuat
		{
			get
			{
				return this._HangSanXuat;
			}
			set
			{
				if ((this._HangSanXuat != value))
				{
					this.OnHangSanXuatChanging(value);
					this.SendPropertyChanging();
					this._HangSanXuat = value;
					this.SendPropertyChanged("HangSanXuat");
					this.OnHangSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGheLTG", DbType="Int NOT NULL")]
		public int SoGheLTG
		{
			get
			{
				return this._SoGheLTG;
			}
			set
			{
				if ((this._SoGheLTG != value))
				{
					this.OnSoGheLTGChanging(value);
					this.SendPropertyChanging();
					this._SoGheLTG = value;
					this.SendPropertyChanged("SoGheLTG");
					this.OnSoGheLTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGheLT", DbType="Int NOT NULL")]
		public int SoGheLT
		{
			get
			{
				return this._SoGheLT;
			}
			set
			{
				if ((this._SoGheLT != value))
				{
					this.OnSoGheLTChanging(value);
					this.SendPropertyChanging();
					this._SoGheLT = value;
					this.SendPropertyChanged("SoGheLT");
					this.OnSoGheLTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAYBAY_CHUYENBAY", Storage="_CHUYENBAYs", ThisKey="MaMayBay", OtherKey="MaMayBay")]
		public EntitySet<CHUYENBAY> CHUYENBAYs
		{
			get
			{
				return this._CHUYENBAYs;
			}
			set
			{
				this._CHUYENBAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.MAYBAY = this;
		}
		
		private void detach_CHUYENBAYs(CHUYENBAY entity)
		{
			this.SendPropertyChanging();
			entity.MAYBAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _NgaySinh;
		
		private bool _GioiTinh;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _ChucVu;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _AnhNV;
		
		private EntitySet<VEBAN> _VEBANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnAnhNVChanging(string value);
    partial void OnAnhNVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._VEBANs = new EntitySet<VEBAN>(new Action<VEBAN>(this.attach_VEBANs), new Action<VEBAN>(this.detach_VEBANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhNV", DbType="NVarChar(50)")]
		public string AnhNV
		{
			get
			{
				return this._AnhNV;
			}
			set
			{
				if ((this._AnhNV != value))
				{
					this.OnAnhNVChanging(value);
					this.SendPropertyChanging();
					this._AnhNV = value;
					this.SendPropertyChanged("AnhNV");
					this.OnAnhNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VEBAN", Storage="_VEBANs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<VEBAN> VEBANs
		{
			get
			{
				return this._VEBANs;
			}
			set
			{
				this._VEBANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_VEBANs(VEBAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGBAO")]
	public partial class THONGBAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThongBao;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThongBaoChanging(int value);
    partial void OnMaThongBaoChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public THONGBAO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThongBao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThongBao
		{
			get
			{
				return this._MaThongBao;
			}
			set
			{
				if ((this._MaThongBao != value))
				{
					this.OnMaThongBaoChanging(value);
					this.SendPropertyChanging();
					this._MaThongBao = value;
					this.SendPropertyChanged("MaThongBao");
					this.OnMaThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(1000)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
